CATEGORY_NAME_MAX_LENGTH: int = 200
GROUPS_NAME_MAX_LENGTH: int = 100
EXPENSES_DESCRIPTION_MAX_LENGTH: int = 200
DECIMAL_FIELDS_MAX_DIGITS: int = 10
DECIMAL_FIELDS_DECIMAL_PLACES: int = 2
MULTI_THREADED_READER_TIMEOUT: int = 60